MainWidget:

<Background>:

    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            pos: self.pos
            size: self.size

#Where all the components will go
<Workspace>:

#Draw layer
<Draw>:

    canvas:

    Background:
        size: root.width,root.height


<MainWidget>:
    Draw:
        size: root.width,root.height


    Workspace:
        id: workspace
        size: root.width/3.5,root.height